package me.prouge.tryjump.core.utils;

public enum Message {
    PLAYER_JOIN_MESSAGE,
    PLAYER_QUIT_MESSAGE,
    LOBBY_COUNTDOWN,
    LOBBY_TELEPORT,
    LOBBY_ACTIONBAR,
    SETUP_SPAWN_SET,
    GAME_COUNTDOWN,

    GAME_ACTIONBAR,
    GAME_GO,
    GAME_COINS_ADD,
    LOBBY_SHOP_SKIP,
    LOBBY_SHOP_SKIPPED,
    LOBBY_SHOP_SKIPPED_ALREADY


}
